name: this_one

on: workflow_dispatch

jobs:
  this_one:
    name: this_one
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ github.ref }}'
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('context.ref', context.ref)
            console.log('context', context)
