name: this_one

on: workflow_dispatch

jobs:
  this_one:
    name: this_one
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ github.ref }}'
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.MOVE2KUBE_PATOKEN }}
          script: |
            const stellar = JSON.parse('[{"owner": "kon", "repo": "yo", "release_id": 42}]');
            console.log('stellar:', stellar);

            console.log('context.repo', context.repo);
            console.log('context', context);
            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'yohoo',
              workflow_id:'a-new-one.yml',
              ref:context.ref,
            });
