name: PR Build

on:
  pull_request:
    branches:
      - main
      - "release-*"

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref }}
      - run: echo ${{ github.ref == 'refs/heads/main' }}
      - run: echo ${{ github.event }}
      - run: echo ${{ github.event.inputs }}
      - run: echo ${{ github.event.payload }}
      - run: echo ${{ github.event.branches }}
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // console.log('github', github)
            // console.log('context', context)
            console.log('hello');
