name: commit test

on:
  workflow_dispatch:
    inputs:
      json:
        description: the json data
        required: true
        default: '{"some":"thing"}'

jobs:
  foobar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: yoyo
      - run: echo 'run_id ${{ github.run_id }}' > foobar.json
      - run: echo 'input ${{ github.event.inputs.json }}' >> foobar.json
      - uses: EndBug/add-and-commit@v6
        with:
          add: foobar.json
          author_name: commit workflow
          author_email: harikrishmenon@gmail.com
          branch: yoyo
          cwd: "."
          message: update the foobar file with latest info
          pull_strategy: "--ff-only"
          token: ${{ secrets.GITHUB_TOKEN }}
