name: hmm

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "foobar"
        required: true
        default: "v0.1.0"

jobs:
  foobar:
    runs-on: ubuntu-latest
    steps:
      - id: semver_parser
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ github.event.inputs.tag }}
      - run: |
          echo ${{ steps.semver_parser.outputs.major }}
          echo ${{ steps.semver_parser.outputs.minor }}
          echo ${{ steps.semver_parser.outputs.patch }}
          echo ${{ steps.semver_parser.outputs.prerelease }}
          echo ${{ steps.semver_parser.outputs.build }}
          echo ${{ steps.semver_parser.outputs.fullversion }}
          if [[ '${{ steps.semver_parser.outputs.prerelease }}' ]] ; then
            echo 'true'
          else
            echo 'false'
          fi
      - id: logging
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('console.log', context.repo)
            core.info(`core.info, ${JSON.stringify(context.repo)}`)
            core.debug(`core.debug ${JSON.stringify(context.repo)}`)
