name: Label PRs

on:
  pull_request_target:
    types: [opened, edited, reopened]

jobs:
  label_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_welcome_msg = `Thanks for opening this pull request!`;

            if(context.payload.pull_request.comments === 0) {
              await github.issues.createComment({ ...context.repo, issue_number: context.payload.number, body: pr_welcome_msg});
            }

            const title = context.payload.pull_request.title;
            const results = /^(\w+)(\(\w+\))?!?:/.exec(title);
            if (results === null) core.setFailed(`The title ${title} does not follow conventional commits spec: https://www.conventionalcommits.org/en/v1.0.0/#summary`);

            const pr_type = results[1];
            core.debug(`pr_type:${pr_type}`);
            let label = '';
            switch(pr_type) {
              case 'fix':
              case 'refactor':
              case 'chore':
              case 'docs':
                label = 'fix'; break;
              case 'feat':
                label = 'enhancement'; break;
            }
            core.debug(`label: ${label}`);
            if(label === '')core.setFailed(`Unknown pull request type ${pr_type}`);

            const labels = [label];
            await github.issues.addLabels({ ...context.repo, issue_number: context.payload.number, labels });
