name: Label PRs when the semantic check finishes

on:
  check_run:
    types: [completed]

jobs:
  label_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            core.info('github   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!')
            core.info(`${JSON.stringify(github)}`)
            core.info('context  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!')
            core.info(`${JSON.stringify(context)}`)
