name: Label PRs

on:
  pull_request_target:
    types: [opened, edited, reopened]

jobs:
  label_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // core.info('github   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!')
            // core.info(`${JSON.stringify(github)}`)
            // core.info('context  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!')
            // core.info(`${JSON.stringify(context)}`)

            let resp = await github.issues.createComment({ ...context.repo, issue_number: context.payload.number, body: "Thanks for opening this pull request!" });
            core.info('first   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!')
            core.info(`${JSON.stringify(resp)}`)
            const labels = ['enhancement'];
            resp = await github.issues.addLabels({ ...context.repo, issue_number: context.payload.number, labels });
            core.info('second   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!')
            core.info(`${JSON.stringify(resp)}`)
