name: Label PRs

on:
  pull_request_target:
    types: [opened, edited, reopened]

jobs:
  label_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // core.info('github   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!')
            // core.info(`${JSON.stringify(github)}`)
            // core.info('context  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!')
            // core.info(`${JSON.stringify(context)}`)

            let resp = await github.issues.createComment({ ...context.repo, issue_number: context.payload.number, body: "Thanks for opening this pull request!" });
            core.info('first   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!')
            core.info(`${JSON.stringify(resp)}`)
            if (resp.status > 399) core.setFailed(`Failed to create the comment. Status:${resp.status}`);

            const title = context.payload.pull_request.title;
            const results = /^(\w+)(\(\w+\))?!?:/.exec(title);
            if (results === null) core.setFailed(`The title ${title} does not follow conventional commits spec.`);

            const pr_type = results[1];
            core.debug(`pr_type:${pr_type}`);
            let label = '';
            switch(pr_type) {
              case 'fix':
              case 'refactor':
              case 'chore':
              case 'docs':
                label = 'fix'; break;
              case 'feat':
                label = 'enhancement'; break;
            }
            core.debug(`label: ${label}`);
            if(label === '')core.setFailed(`Unknown pull request type ${pr_type}`);

            const labels = [label];
            resp = await github.issues.addLabels({ ...context.repo, issue_number: context.payload.number, labels });
            core.info('second   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!')
            core.info(`${JSON.stringify(resp)}`)
            if (resp.status > 399) core.setFailed(`Failed to set the labels ${labels} Status:${resp.status}`);
