name: Dispatch And Wait

on: workflow_dispatch

jobs:
  dispatch_and_wait:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.MOVE2KUBE_PATOKEN }}
          script: |
            const owner = 'HarikrishnanBalagopal';
            const repo = 'yohoo';
            const workflow_filename = 'target.yml';
            const commit_ref_to_run_on = 'main';
            const resp = await github.actions.createWorkflowDispatch({
              owner,
              repo,
              workflow_id: workflow_filename,
              ref: commit_ref_to_run_on,
              inputs: {"foo": "bar"},
            });
            console.log(resp);

            function wait(milli_seconds) {
              return new Promise(resolve => {
                setTimeout(() => resolve(), milli_seconds);
              });
            }

            let workflow_runs = [];
            for(let i = 0; i < 3; i++) {
              await wait(2000); // pause 2 seconds to let the workflow get scheduled.
              const resp = await github.actions.listWorkflowRuns({
                owner,
                repo,
                workflow_id: workflow_filename,
                branch: commit_ref_to_run_on,
                event: "workflow_dispatch",
              });
              if(resp.data && resp.data.workflow_runs && resp.data.workflow_runs.length > 0) {
                console.log(resp);
                workflow_runs = resp.data.workflow_runs;
                break;
              }
              if(i === 3) {
                return core.setFailed('Failed to get the workflow run');
              }
            }

            console.log('workflow_runs:');
            for(const workflow_run of workflow_runs) {
              console.log(workflow_run);
            }
