name: Dispatch And Wait

on: workflow_dispatch

jobs:
  dispatch_and_wait:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.MOVE2KUBE_PATOKEN }}
          script: |
            const owner = 'HarikrishnanBalagopal';
            const repo = 'yohoo';
            const workflow_filename = 'target.yml';
            const commit_ref_to_run_on = 'main';
            const resp = await github.actions.createWorkflowDispatch({
              owner,
              repo,
              workflow_id: workflow_filename,
              ref: commit_ref_to_run_on,
              inputs: {"foo": "bar"},
            });
            console.log(resp);

            function wait(milli_seconds) {
              return new Promise(resolve => {
                setTimeout(() => resolve(), milli_seconds);
              });
            }

            // await wait(2000); // pause 2 seconds to let the workflow get scheduled.

            const resp1 = await github.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id: workflow_filename,
              branch: commit_ref_to_run_on,
              event: "workflow_dispatch",
            });
            for(const workflow_run of resp1.data.workflow_runs) {
              console.log(workflow_run);
            }
