name: PR Label

on:
  pull_request:
    branches: [main]
    types: [opened]

jobs:
  label:
    name: Add labels
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ github}}'
      - run: echo '${{ github.event }}'
      - run: echo '${{ github.event.number }}'
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.MOVE2KUBE_PATOKEN }}
          script: |
            const labels = ['bug'];
            core.info(github);
            const resp = await github.issues.addLabels({
              ...context.repo,
              issue_number: ${{ github.event.number }},
              labels
            });
            if (resp.status !== 200) {
              core.setFailed(`Failed to set the labels ${labels} on the PR. Status code: ${resp.status}`)
            }
            core.info(`Successfully set the labels ${labels} on the PR.`)
