name: Tag and Release Test

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "current tag: The tag for this release"
        required: true
        default: v0.1.0-rc.2
      prev_tag:
        description: "previous tag: Tag from which to start calculating the changelog"
        required: false
      commit_ref:
        description: "commit ref: The branch, tag or SHA of the commit to use for the release."
        required: false
        default: main

jobs:
  some:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.inputs.tag }} ${{ github.event.inputs.prev_tag }} ${{ github.event.inputs.commit_ref }}
