name: upload_to_release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "the tag of the release"
        required: true
        default: yo.there.200
      prev_tag:
        description: "the changelog will be computed from this tag onwards"
        required: false

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ github.event.inputs.tag }}",
              sha: context.sha
            })
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: info
        uses: konveyor/get-env-info@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.info.outputs.node_version }}
      - name: create release draft
        shell: bash
        run: |
          npm install github-release-notes@v0.17.3 -g
          if [[ '${{ github.event.inputs.prev_tag }}' ]] ; then
          gren release --draft --prerelease --tags ${{ github.event.inputs.tag }}..${{ github.event.inputs.prev_tag }} --username=${{ github.repository_owner }} --repo=${{ github.event.repository.name }} --token=${{ secrets.GITHUB_TOKEN }}
          else
          gren release --draft --prerelease --tags ${{ github.event.inputs.tag }} --username=${{ github.repository_owner }} --repo=${{ github.event.repository.name }} --token=${{ secrets.GITHUB_TOKEN }}
          fi
      - run: |
          mkdir -p _dist/output/
          echo '${{ secrets.GITHUB_TOKEN }}' > _dist/output/foo
          node --version > _dist/output/bar
      - name: upload release assets
        uses: HarikrishnanBalagopal/upload-release-action@v3
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.tag }}
          file: _dist/output/*
          file_glob: true
          overwrite: true
