name: test go compilation

on: workflow_dispatch

jobs:
  test:
    # runs-on: ubuntu-latest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - run: ls -a
      - id: info
        uses: konveyor/get-env-info@v1
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.info.outputs.go_version }}
      - run: go build
      - run: ls -a
      - run: ./yothere

      - run: go get github.com/mitchellh/gox@v1.0.1
      - run: |
          CGO_ENABLED=0 gox -parallel=3 -output="myoutput/{{.OS}}-{{.Arch}}/yothere" -osarch='darwin/amd64 linux/amd64' .
      - run: ls -R
      # - run: ./myoutput/linux-amd64/yothere
      - run: ./myoutput/darwin-amd64/yothere
      - uses: actions/upload-artifact@v2
        with:
          name: before-compress
          path: ./myoutput/darwin-amd64/yothere

      - run: brew install upx
      - run: brew ls
      - run: upx --version

      - run: cd ./myoutput/darwin-amd64/ && upx yothere && cd -
      - run: ./myoutput/darwin-amd64/yothere
      - uses: actions/upload-artifact@v2
        with:
          name: after-compress
          path: ./myoutput/darwin-amd64/yothere

      - run: cd ./myoutput/darwin-amd64/ && upx -d yothere && cd -
      - run: ./myoutput/darwin-amd64/yothere
      - run: echo "done"
      - uses: actions/upload-artifact@v2
        with:
          name: after-de-compress
          path: ./myoutput/darwin-amd64/yothere
