name: test mac security

on: workflow_dispatch

jobs:
  test:
    runs-on: macos-latest
    steps:
      - run: wget https://github.com/HarikrishnanBalagopal/yothere/raw/main/my-dist.zip
      - run: ls -R
