name: What

on:
  push:
    branches:
      - main
      - "release-*"

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          ls -a
          echo 'github ${{ github }}'
          echo 'github.sha  ${{ github.sha }}'
          echo 'github.ref  ${{ github.ref }}'
          echo 'context ${{ context }}'
          echo 'context.ref ${{ context.ref }}'
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.MOVE2KUBE_PATOKEN }}
          script: |
            core.info(`github: ${JSON.stringify(github)}`)
            core.info(`context: ${JSON.stringify(context)}`)
